# Generated by Django 2.1.7 on 2019-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedactedClientConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('cookies', models.TextField(null=True)),
                ('authkey', models.TextField(null=True)),
                ('passkey', models.TextField(null=True)),
                ('last_login_failed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RedactedThrottledRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('url', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
