# Generated by Django 2.1.7 on 2019-02-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedclientconfig',
            name='cookies',
            field=models.BinaryField(null=True),
        ),
    ]
