# Generated by Django 2.1.7 on 2019-03-02 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0003_redactedclientconfig_login_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactedTorrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_datetime', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
                ('info_hash', models.CharField(max_length=40)),
                ('media', models.CharField(max_length=64)),
                ('format', models.CharField(max_length=64)),
                ('encoding', models.CharField(max_length=64)),
                ('remastered', models.BooleanField()),
                ('remaster_year', models.IntegerField()),
                ('remaster_title', models.CharField(max_length=65536)),
                ('remaster_record_label', models.CharField(max_length=65536)),
                ('remaster_catalog_number', models.CharField(max_length=65536)),
                ('scene', models.BooleanField()),
                ('has_log', models.BooleanField()),
                ('has_cue', models.BooleanField()),
                ('log_score', models.IntegerField(null=True)),
                ('file_count', models.IntegerField()),
                ('size', models.BigIntegerField()),
                ('seeders', models.IntegerField()),
                ('leechers', models.IntegerField()),
                ('snatched', models.IntegerField()),
                ('free_torrent', models.BooleanField()),
                ('reported', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('file_list', models.TextField()),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=65536)),
            ],
        ),
        migrations.CreateModel(
            name='RedactedTorrentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_datetime', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
                ('name', models.CharField(max_length=65536)),
                ('year', models.IntegerField()),
                ('record_label', models.CharField(max_length=65536)),
                ('catalog_number', models.CharField(max_length=65536)),
                ('release_type', models.IntegerField()),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=65536)),
                ('time', models.DateTimeField()),
                ('vanity_house', models.BooleanField()),
                ('is_bookmarked', models.BooleanField()),
                ('music_info', models.TextField()),
                ('tags', models.TextField()),
                ('wiki_body', models.TextField()),
                ('wiki_image', models.CharField(max_length=65536)),
            ],
        ),
        migrations.AddField(
            model_name='redactedtorrent',
            name='torrent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='redacted.RedactedTorrentGroup'),
        ),
    ]
