# Generated by Django 2.1.7 on 2019-03-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0015_torrentinfo_is_deleted'),
        ('redacted', '0004_auto_20190302_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactedtorrent',
            name='torrent_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='redacted_torrent', to='torrents.TorrentInfo'),
            preserve_default=False,
        ),
    ]
