# Generated by Django 2.1.7 on 2019-03-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0005_redactedtorrent_torrent_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedtorrent',
            name='remaster_catalog_number',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='redactedtorrent',
            name='remaster_record_label',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='redactedtorrent',
            name='remaster_title',
            field=models.CharField(max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='redactedtorrent',
            name='remaster_year',
            field=models.IntegerField(null=True),
        ),
    ]
