# Generated by Django 2.1.7 on 2019-03-22 10:30

from django.db import migrations
import torrents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0006_auto_20190303_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedtorrent',
            name='info_hash',
            field=torrents.fields.InfoHashField(db_index=True, max_length=40),
        ),
    ]
