# Generated by Django 2.1.7 on 2019-03-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0007_auto_20190322_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedtorrent',
            name='encoding',
            field=models.CharField(choices=[('192', '192'), ('APS (VBR)', 'APS (VBR)'), ('V2 (VBR)', 'V2 (VBR)'), ('V1 (VBR)', 'V1 (VBR)'), ('256', '256'), ('APX (VBR)', 'APX (VBR)'), ('V0 (VBR)', 'V0 (VBR)'), ('320', '320'), ('Lossless', 'Lossless'), ('24bit Lossless', '24bit Lossless'), ('Other', 'Other')], max_length=64),
        ),
        migrations.AlterField(
            model_name='redactedtorrent',
            name='format',
            field=models.CharField(choices=[('MP3', 'MP3'), ('FLAC', 'FLAC'), ('AAC', 'AAC'), ('AC3', 'AC3'), ('DTS', 'DTS')], max_length=64),
        ),
        migrations.AlterField(
            model_name='redactedtorrent',
            name='media',
            field=models.CharField(choices=[('CD', 'CD'), ('DVD', 'DVD'), ('Vinyl', 'Vinyl'), ('Soundboard', 'Soundboard'), ('SACD', 'SACD'), ('DAT', 'DAT'), ('Cassette', 'Cassette'), ('WEB', 'WEB'), ('Blu-Ray', 'Blu-Ray')], max_length=64),
        ),
    ]
