# Generated by Django 2.1.7 on 2019-03-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0008_auto_20190331_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redactedtorrentgroup',
            old_name='music_info',
            new_name='music_info_json',
        ),
    ]
