# Generated by Django 2.1.7 on 2019-04-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0009_auto_20190401_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactedRequestCacheEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_datetime', models.DateTimeField()),
                ('action', models.CharField(max_length=128)),
                ('kwargs_json', models.CharField(max_length=65536)),
                ('response_json', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='redactedrequestcacheentry',
            unique_together={('action', 'kwargs_json')},
        ),
    ]
