# Generated by Django 2.1.7 on 2020-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0010_auto_20190408_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redactedclientconfig',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='redactedclientconfig',
            name='password',
        ),
        migrations.RemoveField(
            model_name='redactedclientconfig',
            name='username',
        ),
        migrations.AddField(
            model_name='redactedclientconfig',
            name='api_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
