# Generated by Django 2.1.7 on 2020-09-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0011_auto_20200921_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactedclientconfig',
            name='announce_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
