# Generated by Django 3.1.2 on 2020-10-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0012_redactedclientconfig_announce_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactedArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_datetime', models.DateTimeField(db_index=True, null=True)),
                ('is_deleted', models.BooleanField()),
                ('name', models.CharField(max_length=65536, null=True)),
                ('image', models.CharField(max_length=65536, null=True)),
                ('body', models.TextField(null=True)),
                ('vanity_house', models.BooleanField(null=True)),
                ('tags', models.JSONField(null=True)),
                ('similar_artists', models.JSONField(null=True)),
                ('statistics', models.JSONField(null=True)),
                ('torrent_groups', models.JSONField(null=True)),
                ('requests', models.JSONField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='redactedtorrent',
            name='fetched_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
