# Generated by Django 3.1.2 on 2020-10-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0013_auto_20201018_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedtorrentgroup',
            name='music_info_json',
            field=models.JSONField(),
        ),
    ]
