# Generated by Django 3.1.2 on 2020-10-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0015_auto_20201018_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedtorrentgroup',
            name='fetched_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
