# Generated by Django 3.1.2 on 2020-10-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redacted', '0016_auto_20201018_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactedtorrentgroup',
            name='music_info',
            field=models.JSONField(null=True),
        ),
    ]
