# Generated by Django 2.1.7 on 2019-03-30 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('media_type', models.CharField(choices=[('music', 'music')], max_length=64)),
                ('current_step', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('warnings', 'warnings'), ('errors', 'errors'), ('complete', 'complete'), ('finished', 'finished')], default='pending', max_length=64)),
                ('executor_name', models.CharField(max_length=64)),
                ('executor_kwargs_json', models.TextField()),
                ('metadata_json', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_studio.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStepError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_studio.ProjectStep')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStepWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(unique=True)),
                ('acked', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_studio.ProjectStep')),
            ],
        ),
    ]
