# Generated by Django 2.1.7 on 2019-03-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_studio', '0002_auto_20190331_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
