# Generated by Django 2.1.7 on 2019-03-31 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_studio', '0003_project_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
