# Generated by Django 2.1.7 on 2019-03-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0024_auto_20190327_0137'),
        ('upload_studio', '0004_auto_20190331_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_torrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='torrents.Torrent'),
        ),
    ]
