# Generated by Django 2.1.7 on 2019-04-05 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_studio', '0006_auto_20190402_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
