# Generated by Django 2.1.7 on 2019-04-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_studio', '0008_auto_20190407_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsteperror',
            options={'ordering': ('message',)},
        ),
        migrations.AlterModelOptions(
            name='projectstepwarning',
            options={'ordering': ('message',)},
        ),
    ]
