# Generated by Django 2.1.7 on 2019-04-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_studio', '0009_auto_20190407_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finished_datetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
