# Generated by Django 2.1.7 on 2020-10-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_studio', '0011_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_external',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
