# Generated by Django 2.1.7 on 2020-10-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_studio', '0012_project_source_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgurConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=512, null=True)),
                ('client_secret', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
