# Generated by Django 2.1.7 on 2019-04-08 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Executing'), (2, 'Succeeded'), (3, 'Errored'), (4, 'Timed Out')], default=0)),
                ('handler', models.CharField(max_length=128)),
                ('args_pickle', models.BinaryField()),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_datetime', models.DateTimeField(null=True)),
                ('completed_datetime', models.DateTimeField(null=True)),
            ],
        ),
    ]
