# Generated by Django 2.1.7 on 2019-04-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='traceback',
            field=models.TextField(null=True),
        ),
    ]
