# Generated by Django 2.1.7 on 2019-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_queue', '0002_asynctask_traceback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynctask',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Executing'), (2, 'Succeeded'), (3, 'Errored'), (4, 'Timed Out')], db_index=True, default=0),
        ),
    ]
