# Generated by Django 2.1.7 on 2019-02-17 14:50
# Generated by Django 2.1.7 on 2019-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(db_index=True, max_length=40)),
                ('name', models.TextField(null=True)),
                ('size', models.BigIntegerField(null=True)),
                ('uploaded', models.BigIntegerField(null=True)),
                ('progress', models.FloatField(null=True)),
                ('date_added', models.DateTimeField(null=True)),
                ('error', models.CharField(max_length=65536)),
                ('tracker_error', models.CharField(max_length=65536)),
            ],
        ),
    ]
