# Generated by Django 2.1.7 on 2019-02-21 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcazarConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=2048)),
                ('token', models.CharField(max_length=64)),
                ('last_poll', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TorrentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('torrent_file', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='TorrentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(db_index=True, max_length=40)),
                ('tracker_id', models.CharField(max_length=64)),
                ('fetched_datetime', models.DateTimeField()),
                ('raw_response', models.TextField()),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torrent_infos', to='torrents.Realm')),
            ],
        ),
        migrations.RenameField(
            model_name='torrent',
            old_name='date_added',
            new_name='added_datetime',
        ),
        migrations.AlterField(
            model_name='torrent',
            name='error',
            field=models.TextField(max_length=65536),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='tracker_error',
            field=models.TextField(max_length=65536),
        ),
        migrations.AddField(
            model_name='torrentfile',
            name='torrent_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='torrents.TorrentInfo'),
        ),
        migrations.AddField(
            model_name='torrent',
            name='realm',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='torrents', to='torrents.Realm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torrent',
            name='torrent_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='torrent', to='torrents.TorrentInfo'),
        ),
    ]
