# Generated by Django 2.1.7 on 2019-02-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0002_auto_20190221_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcazarClientConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=2048)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='AlcazarConfig',
        ),
    ]
