# Generated by Django 2.1.7 on 2019-02-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0003_auto_20190222_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='download_location',
            field=models.CharField(default='', max_length=65536),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realm',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='torrent',
            unique_together={('realm', 'info_hash')},
        ),
        migrations.AlterUniqueTogether(
            name='torrentinfo',
            unique_together={('realm', 'info_hash')},
        ),
    ]
