# Generated by Django 2.1.7 on 2019-02-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0004_auto_20190222_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='tracker_error',
        ),
        migrations.AlterField(
            model_name='torrent',
            name='error',
            field=models.TextField(max_length=65536, null=True),
        ),
    ]
