# Generated by Django 2.1.7 on 2019-02-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0005_auto_20190222_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentfile',
            name='torrent_filename',
            field=models.CharField(default='', max_length=65536),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torrentinfo',
            name='tracker_id',
            field=models.CharField(max_length=65536),
        ),
    ]
