# Generated by Django 2.1.7 on 2019-02-23 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0007_auto_20190223_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentfile',
            name='fetched_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 1, 34, 26, 867955, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
