# Generated by Django 2.1.7 on 2019-02-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0008_torrentfile_fetched_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='torrentinfo',
            unique_together={('realm', 'info_hash'), ('realm', 'tracker_id')},
        ),
    ]
