# Generated by Django 2.1.7 on 2019-02-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0009_auto_20190223_0136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='torrentinfo',
            unique_together={('realm', 'tracker_id')},
        ),
        migrations.AlterIndexTogether(
            name='torrentinfo',
            index_together={('realm', 'info_hash')},
        ),
    ]
