# Generated by Django 2.1.7 on 2019-02-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0011_auto_20190223_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='download_rate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='torrent',
            name='downloaded',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='torrent',
            name='upload_rate',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='error',
            field=models.TextField(db_index=True, max_length=65536, null=True),
        ),
    ]
