# Generated by Django 2.1.7 on 2019-03-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0013_downloadlocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlocation',
            options={'ordering': ('realm', 'pattern')},
        ),
        migrations.AlterUniqueTogether(
            name='downloadlocation',
            unique_together={('realm', 'pattern')},
        ),
    ]
