# Generated by Django 2.1.7 on 2019-03-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0014_auto_20190302_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentinfo',
            name='is_deleted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
