# Generated by Django 2.1.7 on 2019-03-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0016_torrent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='tracker_error',
            field=models.TextField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='torrent',
            name='error',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
