# Generated by Django 2.1.7 on 2019-03-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0017_auto_20190303_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrent',
            name='client',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
