# Generated by Django 2.1.7 on 2019-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0018_torrent_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcazarclientconfig',
            name='unify_single_file_torrents',
            field=models.BooleanField(default=False),
        ),
    ]
