# Generated by Django 2.1.7 on 2019-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0019_alcazarclientconfig_unify_single_file_torrents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcazarclientconfig',
            name='token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
