# Generated by Django 2.1.7 on 2019-03-22 10:30

from django.db import migrations
import torrents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0020_auto_20190319_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='info_hash',
            field=torrents.fields.InfoHashField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='torrentinfo',
            name='info_hash',
            field=torrents.fields.InfoHashField(db_index=True, max_length=40),
        ),
    ]
