# Generated by Django 2.1.7 on 2019-03-26 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('torrents', '0022_torrentinfo_raw_response_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrentinfo',
            name='raw_response',
        ),
        migrations.RenameField(
            model_name='torrentinfo',
            old_name='raw_response_binary',
            new_name='raw_response',
        ),
    ]
