# Generated by Django 2.1.7 on 2019-03-27 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0023_rename_raw_response_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='added_datetime',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
