# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder "../..", "/vagrant"
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/hashicorp/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "deployment/vagrant-dev/playbook.yml"
    ansible.compatibility_mode = "2.0"
  end
end
